=== zbatul/Web-Development/Club Website Design/clubServer/activitySchema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://DrBsclasses.org/student47/node/activities",
    "title": "Activity",
    "description": "A club activity for the schedule",
    "type": "object",
    "properties": {
        "activity": {
            "type": "string",
            "minLength": 1,
            "maxLength": 40
        },
        "timings": {
            "description": "the date(s) or timing(s) of the activity",
            "type": "string",
            "minLength": 1,
            "maxLength": 100
        },
        "items": {
            "description": "items required for the activity",
            "type": "array"
        },
        "desc": {
            "description": "the description of activity",
            "type": "string",
            "maxLength": 200
        }
    },
    "required": ["activity", "timings"],
    "additionalProperties": false
}

=== zbatul/Web-Development/Club Website Design/clubReact/eventData.json
[
    {
        "activity": "Beginner Knitting",
        "timings": "4:00PM - 6:00PM, Mon-Fri",
        "items": ["Yarn", "Scissors", "Tapestry Needle", "Knitting Needles"],
        "desc": "Don't know knitting or just started? Join our knitting community. Get inspired. Start with simple English knitting with other beginners like you. Complete your beginner knitting project with easy-to-follow-step-by-step-patterns."
    },
    {
        "activity": "Intermediate Knitting",
        "timings": "6:00PM - 8:00PM, Mon-Sat",
        "items": ["Yarn", "Scissors", "Tapestry Needle", "Knitting Needles", "Stitch Markers"],
        "desc": "You know what a bliss knitting is but can't find time to complete your project? Join our knitting sessions. Get motivated. Finish your projects. Share your knitting tips with other knitters. Share your patterns. Motivate others."
    },
    {
        "activity": "Advanced Knitting",
        "timings": "9:00AM - 1:00PM, Every-Day",
        "items": ["As per your Pattern and Project needs"],
        "desc": "Willing to try new challenges or are you holding yourself back? Join other knitters like you. Combine techniques. Learn new ones. Take your skills to the next level. Complete your dream project."
    }
]
