=== zbatul/Web-Development/Club Website Design/clubServer/memberSchema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://DrBsclasses.org/student47/node/members",
    "title": "Member",
    "description": "A club member information",
    "type": "object",
    "properties": {
        "firstName": {
            "type": "string",
            "minLength": 1,
            "maxLength": 26
        },
		"lastName": {
            "type": "string",
            "minLength": 1,
            "maxLength": 26
        },
		"email": {
			"type": "string",
			"format": "email",
			"minLength": 3,
			"maxLength": 64
		},
        "role": {
            "description": "role of the user: guest, member or admin",
            "type": "string"
        },
		"passHash": {
			"description": "Hashed password of user",
			"type": "string"
		}
    },
    "required": ["firstName", "lastName", "email", "role", "passHash"],
    "additionalProperties": true
}

=== zbatul/Web-Development/Club Website Design/clubServer/clubUsersHash.json
[
  {
    "firstName": "Melia",
    "lastName": "Barker",
    "email": "tirrivees1820@outlook.com",
    "passHash": "$2a$13$kWqq5GaE6A0GrBBDRoG0c.JwXPN7aZRKnR4.D.4n/K0.uVoJlefYa",
    "role": "admin"
  },
  {
    "firstName": "Demetrice",
    "lastName": "Parker",
    "email": "chihuahua1899@gmail.com",
    "passHash": "$2a$13$fYEPNw.ScGhuk/wuosnkFe.1ptfku.c2qFWXvt46O9Hk1OifkLQoa",
    "role": "member"
  },
  {
    "firstName": "Ligia",
    "lastName": "Hudson",
    "email": "umbrate1989@yahoo.com",
    "passHash": "$2a$13$4vj6Jl1UcA9kNbxQlxSxW.hCm9qWlMBAp4DVyFKUmfCGHyWszea.W",
    "role": "member"
  },
  {
    "firstName": "Maisha",
    "lastName": "Hickman",
    "email": "bibiri1807@yandex.com",
    "passHash": "$2a$13$aZIo4N3nWIh4CclRxzj5Ze/79C8FcOCiwC7cQz0pBC62m2m93k/OK",
    "role": "member"
  },
  {
    "firstName": "Cythia",
    "lastName": "Park",
    "email": "biune1929@gmail.com",
    "passHash": "$2a$13$OxkOo9oHvLRmp50d4Ii2b.Gn8G18gUAPBEmTnWl2cmCfpnMuGJ2Ri",
    "role": "member"
  },
  {
    "firstName": "Arlie",
    "lastName": "Holt",
    "email": "aromatised1858@yandex.com",
    "passHash": "$2a$13$nXmEF6nlwfOnQMgoWJREPOymhmIcbnjG30tuPY3NdcrqnnP.yADNe",
    "role": "member"
  },
  {
    "firstName": "Andy",
    "lastName": "Morton",
    "email": "bayesian1899@outlook.com",
    "passHash": "$2a$13$.gbEFTBfz/j81n1/JUy8oOwLJ6/lEZDK3br085DXznYTacsvoh16.",
    "role": "member"
  },
  {
    "firstName": "Peg",
    "lastName": "Gardner",
    "email": "earrings1987@yandex.com",
    "passHash": "$2a$13$SAOYZFfHBDWCxfYBjeS4cOpkLj.LI.JBYq84vWzlEOekEG8MlS1sW",
    "role": "member"
  },
  {
    "firstName": "Noble",
    "lastName": "Wilder",
    "email": "facer1912@yandex.com",
    "passHash": "$2a$13$nEwm43LBeTqkX45mDJlxPOhdTxz7daEfR9sTkAlyN2LVlBXUfkUMy",
    "role": "member"
  },
  {
    "firstName": "Willow",
    "lastName": "Trevino",
    "email": "nodes1883@yahoo.com",
    "passHash": "$2a$13$ODwyOG9TZej8sE9cNlyoEO.oVqEB.5wr5IaKieJKYiZLj7ZAJrIke",
    "role": "member"
  },
  {
    "firstName": "Corrinne",
    "lastName": "Curtis",
    "email": "boisset1829@live.com",
    "passHash": "$2a$13$agoJdOu9ZVnPd8FG7I7Dzud7HqKppxUi6R12oXcn0FbGpY6msKxgK",
    "role": "member"
  },
  {
    "firstName": "Joseph",
    "lastName": "Brock",
    "email": "utilizer1910@live.com",
    "passHash": "$2a$13$DDPP32BWMBT.I9xvwGgksOIfSVIbwg2WfK5mdtkTmd9f2fg54g64C",
    "role": "member"
  },
  {
    "firstName": "Daron",
    "lastName": "Stevens",
    "email": "pedocalcic1982@outlook.com",
    "passHash": "$2a$13$u4fwsvr9Xl873gZSa6oNYuJLNN9fDiDh/qeM6cz79C8D09M7.q4g2",
    "role": "member"
  },
  {
    "firstName": "Anamaria",
    "lastName": "Grant",
    "email": "downtown1843@live.com",
    "passHash": "$2a$13$IHyLF9Q.Jou/vsN.OjQWq.KLf/ndQMsoD6wDOvmHhRRCpKnwKcwb.",
    "role": "member"
  },
  {
    "firstName": "Leonard",
    "lastName": "Shepherd",
    "email": "thrower1972@yahoo.com",
    "passHash": "$2a$13$.0JcskAxB5TmGIcB5LrQjeRY8AwgS3GwVOjDatkG5kyW.KuhydQf6",
    "role": "member"
  },
  {
    "firstName": "Belia",
    "lastName": "Monroe",
    "email": "cranky1882@gmail.com",
    "passHash": "$2a$13$8I1tInVqC2BHqG6IjNiyuuzt7D6Lr9RKi9RS4BDIpzJM0cVKmA6qW",
    "role": "member"
  },
  {
    "firstName": "Stacey",
    "lastName": "Calderon",
    "email": "marsileaceae1910@gmail.com",
    "passHash": "$2a$13$iY5Hb4UhW..pXzf4D1fBk.jdU7c67ODw5t33X8CIhXafMCqT.3FPi",
    "role": "member"
  },
  {
    "firstName": "Bob",
    "lastName": "Fitzgerald",
    "email": "burin1898@yahoo.com",
    "passHash": "$2a$13$s3JaKh.Jk1n4/pDTqJLjZ.3jlGV476ThuQX51yAx7XtaBK4TpCp2K",
    "role": "member"
  },
  {
    "firstName": "Albertina",
    "lastName": "Mclaughlin",
    "email": "drainpipe2041@yandex.com",
    "passHash": "$2a$13$IRu3iz0.zd5bjIFWAG3g2.833HRyIwE8s0qGABCtQOhpMaJJfFLFm",
    "role": "member"
  },
  {
    "firstName": "Marg",
    "lastName": "Carney",
    "email": "ventages2031@yahoo.com",
    "passHash": "$2a$13$mRzCL2QHI/NBVSF3LuUrueOYylFNd7zlhnlfMHxXoZU4rcUvbTfjK",
    "role": "member"
  },
  {
    "firstName": "Jeffery",
    "lastName": "Charles",
    "email": "zaffer1889@live.com",
    "passHash": "$2a$13$tdQcq33c5b4RmyAJSo39NuDgnyrm3FYJSTHC4emkmA2uAxRkd/NsC",
    "role": "member"
  },
  {
    "firstName": "Annett",
    "lastName": "Parsons",
    "email": "kurikata1944@yandex.com",
    "passHash": "$2a$13$m6t1A0nKF74NI4kFdWYelO8QP4lp0sRK9g6HmY0k.DdEmD8lV03Vq",
    "role": "member"
  },
  {
    "firstName": "Wilson",
    "lastName": "Sharpe",
    "email": "misunderstandable1916@live.com",
    "passHash": "$2a$13$LUtPyaHw5y9YBwz7ZpYfyuazpdo5BU/6hQQscbGsEUDHsDmrYnR6a",
    "role": "member"
  },
  {
    "firstName": "Gertude",
    "lastName": "Ewing",
    "email": "althein1801@yahoo.com",
    "passHash": "$2a$13$9RBOBcCkzfx2rLNdg0yLMOIFvp2SmS3D.OQtHRygPRp.rnLDfPD26",
    "role": "member"
  },
  {
    "firstName": "Phil",
    "lastName": "Knowles",
    "email": "piscators1880@live.com",
    "passHash": "$2a$13$3g5xzXnHYIKz5C85W8i41OnD/6sBBxQvHD54HIV3zKX.3JTTmJ6IS",
    "role": "member"
  },
  {
    "firstName": "Catherina",
    "lastName": "Castillo",
    "email": "saltworker1892@live.com",
    "passHash": "$2a$13$AVdUHWLxVSbSg5rnT3Ir0.IJ9m1Al3TeDdckGrh/1883rJKSTMpVy",
    "role": "member"
  },
  {
    "firstName": "Jim",
    "lastName": "Kennedy",
    "email": "speer2026@outlook.com",
    "passHash": "$2a$13$fK0ALnNf/.aJKcd/cgMM7.SbdMnyjlWcdDReAplx9iqCSSSlBlno6",
    "role": "member"
  },
  {
    "firstName": "Tula",
    "lastName": "Stafford",
    "email": "devoir1853@live.com",
    "passHash": "$2a$13$xTqke3qZ5aaHYANhGqiIhuzWv8jdfbEcAGpUeaJfDs5AMr6ih2/hK",
    "role": "member"
  },
  {
    "firstName": "Rachell",
    "lastName": "Harding",
    "email": "article1896@outlook.com",
    "passHash": "$2a$13$pz75qQXerzbTSd7vSZ37YuhIkHtkxD.E64AQTmb5qL/vsKYBu2e82",
    "role": "member"
  },
  {
    "firstName": "Brandon",
    "lastName": "Monroe",
    "email": "article1821@live.com",
    "passHash": "$2a$13$YW/7e5q2tlU5S.SY7St4ueIOmDfz.R1CkQ2nVW8Jv2O.LWWjy9muS",
    "role": "member"
  },
  {
    "firstName": "Micha",
    "lastName": "Sanders",
    "email": "fewer1818@outlook.com",
    "passHash": "$2a$13$rwEewcgsskk0sIF.JGVCjeVPSbyawgy.repqCoqL0Yz2dJ9EoA9/q",
    "role": "member"
  },
  {
    "firstName": "Blake",
    "lastName": "Gray",
    "email": "occults1985@yandex.com",
    "passHash": "$2a$13$7oIVMo/QsyWmujQ/LV/4Ie.gYu82/nh2HEbkdR6iErZ8F7QQl6vUK",
    "role": "member"
  },
  {
    "firstName": "Karren",
    "lastName": "Crosby",
    "email": "harborers2000@live.com",
    "passHash": "$2a$13$YOV22sK6pcyvLhict7vnD.1czm5hJ/nJf/spD4/QSaWqDzCDaNWXa",
    "role": "member"
  },
  {
    "firstName": "Faustino",
    "lastName": "Morris",
    "email": "bayard1928@outlook.com",
    "passHash": "$2a$13$V5Zo8Sh1jFjKywn1K8loVeU/k7MClF7/nWzXQTUTgR2Enzasl1Df.",
    "role": "member"
  },
  {
    "firstName": "Claretta",
    "lastName": "Cummings",
    "email": "fish2004@gmail.com",
    "passHash": "$2a$13$LKhxG0FwlvoR7yIoIy9aBOovNX7UmCjW8U/CqH16zPB4ACoHgNDKm",
    "role": "member"
  },
  {
    "firstName": "Carmen",
    "lastName": "Phillips",
    "email": "geometry1853@live.com",
    "passHash": "$2a$13$oBLQF9pReAT6/PK/E.qPy.aNc9SPuDooKn7pvjYpgc5hRW7rtnCgK",
    "role": "member"
  },
  {
    "firstName": "Pamula",
    "lastName": "Holt",
    "email": "amperage1914@yandex.com",
    "passHash": "$2a$13$TUFAJ4wxRStlJX2DWSCZmu5dtJjcuX.Ol9tNMeXwn15Vil1mzySei",
    "role": "member"
  },
  {
    "firstName": "Truman",
    "lastName": "Boyd",
    "email": "dustman2024@live.com",
    "passHash": "$2a$13$wMQ8iNjtfrfRULlL9atjO.9.l6SesJgMr3Z2YmRMOSaiKno5tQZMa",
    "role": "member"
  },
  {
    "firstName": "Alphonso",
    "lastName": "Salazar",
    "email": "raddle2043@yandex.com",
    "passHash": "$2a$13$H1os99SGy/jbZvdFG6qLq.QBfxaqPVOAmhf8PfY/YZHYiD2OTNhcC",
    "role": "member"
  },
  {
    "firstName": "Isidra",
    "lastName": "O'neal",
    "email": "antonin2059@yahoo.com",
    "passHash": "$2a$13$tYbMLl.GdDGgy3ELGF3V9uat1WhHsS3OtALhFS/ULwyhH27j994b.",
    "role": "member"
  }
]
